apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: leeroy-app-gateway
  namespace: progress
spec:
  selector:
    istio: ingressgateway
    namespace: gateways
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"